site_name: FMU-API
site_description: Бесплатная реализация Frontol Mark Unit для работы с маркировкой
site_url: https://shrayky.github.io/FMU-API/
repo_url: https://github.com/shrayky/FMU-API
repo_name: shrayky/FMU-API

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Переключить на темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Переключить на светлую тему
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy
    - navigation.top  # Кнопка "наверх"

plugins:
  - search:
      lang: ru

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

# Явная навигация - убирает дублирование названия
nav:
  - Главная: index.md
