namespace FmuApiDomain.TrueApi.MarkData;

public static class TrueApiGroup
{
    public static int Lp { get; } = 1;
    public static int Shoes { get; } = 2;
    public static int Tobaco { get; } = 3;
    public static int Perfumery { get; } = 4;
    public static int Tires { get; } = 5;
    public static int Electronics { get; } = 6;
    public static int Pharma { get; } = 7;
    public static int Milk { get; } = 8;
    public static int Bicycle { get; } = 9;
    public static int Wheelchairs { get; } = 10;
    public static int Alcohol { get; } = 11;
    public static int Otp { get; } = 12;
    public static int Water { get; } = 13;
    public static int Furs { get; } = 14;
    public static int Beer { get; } = 15;
    public static int Ncp { get; } = 16;
    public static int Bio { get; } = 17;
    public static int Antiseptic { get; } = 19;
    public static int Petfood { get; } = 20;
    public static int Seafood { get; } = 21;
    public static int Nabeer { get; } = 22;
    public static int Softdrinks { get; } = 23;
    public static int Meat { get; } = 25;
    public static int Vetpharma { get; } = 26;
    public static int Toys { get; } = 27;
    public static int Radio { get; } = 28;
    public static int Titan { get; } = 31;
    public static int Conserve { get; } = 32;
    public static int Vegetableoil { get; } = 33;
    public static int Opticfiber { get; } = 34;
    public static int Chemistry { get; } = 35;
    public static int Books { get; } = 36;
    public static int Grocery { get; } = 37;
    public static int Pharmaraw { get; } = 38;
    public static int Construction { get; } = 39;
    public static int Fire { get; } = 40;
    public static int Heater { get; } = 41;
    public static int Cableraw { get; } = 42;
    public static int Autofluids { get; } = 43;
    public static int Polymer { get; } = 44;
    public static int Sweets { get; } = 45;
    public static int Carparts { get; } = 48;
    public static int Furslp { get; } = 49;
    public static int Nicotindev { get; } = 50;
    public static int Gadgets { get; } = 51;
    public static int Frozen { get; } = 52;
    public static int Fertilizers { get; } = 53;
    public static int Homeware { get; } = 54;
    public static int Pyrotechnics { get; } = 59;
}
