<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FirebirdSql.EntityFrameworkCore.Firebird" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\FmuApiDomain\FmuApiDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Workers\" />
  </ItemGroup>

</Project>
